### ISSUE TITLE
Retrieve `local_key` and `dev_id`

### ISSUE THREAD

**Issue by polyedre** [frawau/aiotuya#2]
Hi !
I'm working on a custom component to add a plug sensor to home assistant, it works currently by providing a `local_key`, a `dev_id` and the ip address of the plug.
I tried your work and was amazed when a realised the `local_key` and the `dev_id` were in the `.aiotuya` file !
I only want the "sniffing" part that retrieve these two informations.
The best would be if you could provide a python API that can be just imported and used like this:
```
import aiotuya
listener = aiotuya.listener()
wait(100)
for (id, key) in listener.get_couples():
    print(id, key)
```
If you don't have the time, I can do it. In that case how do you want me to reference your work ? (It would be easier for me to just build an other repo and copy/paste relevant part of your work)

**Comment by frawau** [comment]
Hi,

I am glad you find my little library useful.

You can already do what you want as it is... Check DevManager and DevProvision in __main__.py as well as the use of DevProvision in readin.   That should do it for you.

Cheers

**Comment by frawau** [comment]
One more thing.... Do not abuse the provisioning function of this library. I did include the id and key I got from Tuya so it could be useful.... If we start generating lots of provisioning requests in a short time span, they could possibly notice and rescind that key.  I do not think they will, but we might as well not try that.

Ne tentons pas le diable

**Comment by polyedre** [comment]
Ok thank you !
I succeded to adapt the scanner to my needs.

What I want to do now is to get a way to give all devices in paring mode the informations about the ssid and wifi password (so that they'll begin the udp broadcast to port 6666).
I did'nt found the part of the code that does this (in __main__ or in provision.py) ?

**Comment by frawau** [comment]
From the top of my head, this should work as-is.  (I seem to remember I tried and succeeded with 2 devices).  The SSID and keys are send via the length of some broadcast packets (after a given prelude sequence), so all devices in "pairing" mode should get it.

The key is generated for each device individually.

**Comment by polyedre** [comment]
Yeah, I got it to work by running this function:
```
def sync_plugs(call):
    tuya = TuyaCloud("basic@email.com", "random_pass")
    prov = TuyaProvision(tuya, WIFI_SSID, WIFI_PASSWORD)
    loop = aio.new_event_loop()
    aio.set_event_loop(loop)
    prov.start(loop)
    loop.run_forever()
```

The best for me would be to stop the `loop` event when one device is apaired (I didn't succeed yet)

**Comment by frawau** [comment]
Nothing here for a long time. Closing
