### ISSUE TITLE
ImportError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by WeirdlyChosen** [frawau/aiotuya#7]
Hi, I am grateful you created this tool, however it does not work on my raspbian buster.

here is the traceback:

>   File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/pi/.local/lib/python3.5/site-packages/aiotuya/__init__.py", line 2, in <module>
    from .provision import TuyaProvision, TuyaCloud
  File "/home/pi/.local/lib/python3.5/site-packages/aiotuya/provision.py", line 52, in <module>
    import aiohttp, random,string
ImportError: No module named 'aiohttp'

**Comment by WeirdlyChosen** [comment]
Nevermind, I need to type below to make it work
pip install aiohttp

I do not know if it is appropriate to ask another question in github issues, but aiotuya unable to find my device. Packet capture from mikrotik or android app shows only encrypted SSL requests on my tuya device rebranded by Indonesian company

**Comment by frawau** [comment]
Hi,

I am not sure what you did, but did you provision it first?  If you did not provision with this library it will not know the key it has to use.

Cheers,
    François

**Comment by aviogit** [comment]
This error is just a missing dependency from aiohttp, it happened to me as well.

**Comment by frawau** [comment]
That has been solved (in git)
