### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by guillaumecardon** [frawau/aiotuya#9]
Hello,

I'm very interested to manage my Tuya devices on my Raspberry without use Smartlife, IFTTT or others...
I'm following the instructions :
` python3 -m pip install aiotuya`
Installation of aiotuya OK, with a warning :

> The script aiotuya is installed in '/home/pi/.local/bin' which is not on PATH.

So i add the path to PATH.
`sudo nano .profile`
I write the following instruction at the end of the file
`PATH="/home/pi/.local/bin:$PATH"`

I execute : `python3 -m aiotuya`
Script tell me to "Hit Enter to start", however, i have got only one line "Select Device :"
Nothing else.

I cancel the script, and i execute :
`python3 -m aiotuya -e myemailusedonsmartlifeapp@mail.com -p Mysmartlifepassword -s MyWifiSSID24ghz -P MyWifiPassword24ghz`

It's better !
Script tell me to "Hit Enter to start", i have got only one line "Select Device : [0]     Provision new devices"

I type "0" many times, but script is looping without information.

I cancel the script, and i execute :
`python3 -m aiotuya -e myemailusedonsmartlifeapp@mail.com -p Mysmartlifepassword -s MyWifiSSID24ghz -P MyWifiPassword24ghz -d`

It's better ! 
Script tell me to "Hit Enter to start", i have got only one line "Select Device : [0]     Provision new devices"

I type "0" and i ve got many debug information like this :
`DEBUG: Request is {'a': 'tuya.m.device.list.token', 'deviceId': 'vw9957pc93ml2xxxxxxxxc4yrayj2icr4hy8dwxbtu', 'os': 'Linux', 'lang': 'en', 'v': '1.0', 'clientId': 'kqnykr87dfdffdsf978wcyjvk', 'time': 1581796624, 'postData': '{"token":"kx683g5X"}', 'sid': 'az158144I3317651ndsfK7L36c631a2d26a9dsf8cca3e773afcfccf8'}`

(i've modified these informations)

Script is looping without end...

So how to use it ?  Can i have some examples to detect my devices (i have got only socket) and send a "on" or "off" instruction to a specific socket ?

Thanks for your help !

**Comment by frawau** [comment]
Hi,

That is essentially how you should use it.

First make sure you reset your tuya device to its factory settings.

If you already configured it an know the secret key/device id, you can put it in ~/.aiotuya  

I usually do not enter an email and password, just the SSID and the passphrase (Between quotes if it contains blanks) and let aiotuya manages things. Downside is that the device will not be linked to your account, but that is a plus on my book.

So try that way.


You may also try with a "sudo"

Also, since you added it to your PATH, you do not have to use "python3 -m", you can just use "aiotuya"

Cheers,
    François

**Comment by frawau** [comment]
One more thing, make sure that you are on a machine connected through WiFi... aiotuya need to broadcast things over WiFi for provisioning (after that it is OK to use LAN cable connections)

**Comment by guillaumecardon** [comment]
Thanks for your anwser.
- My raspberry is connected through WIFI (on the same SSID 2.4Ghz), so it's ok for this point.
- No blanks in my SSID and password, it's ok for this point too

- sudo doesn't work on this case : 
```
pi@raspberry:~ $ sudo aiotuya
sudo: aiotuya : commande introuvable
pi@raspberry:~ $ sudo python3 -m aiotuya
/usr/bin/python3: No module named aiotuya
```
I see the ".aiotuya" file. It's created but stay to 0

If i read the log, i see that (in loop, with "time" property increasing) : 
```
  DEBUG: Request is {'a': 'tuya.m.device.list.token', 'deviceId': 'l86goranp054vvg5x6y79bzkksyxsizb2fi99xgdud6b', 'os': 'Linux', 'lang': 'en', 'v': '1.0', 'clientId': 'kqnykr87zerxn99wcyjvk', 'time': 1581841853, 'postData': '{"token":"10ceBzcG"}', 'sid': 'az158184D1824752wjxLJ9w38634b92b6ea65d196b136c7feaed8885'}
  DEBUG: Response to cloud request: []
  DEBUG: Request is {'a': 'tuya.m.device.list.token', 'deviceId': 'l86goranp054vvg5x6y79bzkksyxsizb2fi99xgdud6b', 'os': 'Linux', 'lang': 'en', 'v': '1.0', 'clientId': 'kqnykr87zerxn99wcyjvk', 'time': 1581841854, 'postData': '{"token":"10ceBzcG"}', 'sid': 'az158184D1824752wjxLJ9w38634b92b6ea65d196b136c7feaed8885'}
  DEBUG: Response to cloud request: []

```
So script send a request, but cloud request is empty ? And it try again and again ?

**Comment by frawau** [comment]
Well,

Since you seemed to be doing the right thing, I reset a Tuya lamp I had here and tried to provision it again....

And it failed the same way as you....

 So either the included key was cancelled or something changed in the protocol or both...

It looks like this library can no longer do provisioning

You might want to flash tasmota with https://github.com/ct-Open-Source/tuya-convert

Désolé

**Comment by frawau** [comment]
Update on this.

I did update the code thanks to a PR from another user. So you might want to try this again. (Unless you went the Tasmota route that is)

Also, I did try it on my LAN and it worked. Not sure what I did differently from last time, but I am not using Tuya devices much....

Cheers,
    François

**Comment by guillaumecardon** [comment]
Thanks.
For my part, i used this library : https://github.com/sabinus52/TuyaCloudApi and interact with my Tuya devices by php call...
Maybe a little bit complicated but at this time, it work with no latency.

Thanks again for your help
